version: '3'
services:
  jira-web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jira-web
    ports:
      - 8080:8080
      - 8443:8443
    env_file:
      - .env.jira
    volumes:
      - web:/var/atlassian/jira
    links:
      - jira-db
  jira-db:
    restart: always
    image: mariadb:10.3
    container_name: jira-db
    env_file:
      - .env.db
    volumes:
        - db:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_bin']
volumes:
    web:
    db:
